export const REGISTER_USER = "register_user";
export const LOGIN_USER="login_user";
export const LOGOUT_USER="logout_user";
export const INPUT_DATE='input_date';
export const INPUT_PILL='input_pill';
export const OUTPUT_PILL='ouput_pill';
export const OUTPUT_DATE='output_date';
export const TODAY_DATE='today_date';
export const COLOR_DATE="color_date";